export class MBinConfigDetails {
    constructor() {}    
    id?:number;        
    autoGeneratedCode?:string;        
    levelID?:number;        
    levelName?:string;        
    subLevelCode?:string;        
    subLevelName?:string;        
    headerCode?:string;        
    maxCapacity?:number;        
    binType?:string;        
    defaultReceivingBin?:boolean;        
    defaultSellingBin?:boolean;        
    storeID?:number;        
    storeCode?:string;
    active?:boolean;        
    binLevelDetailsList?: Array<MBinConfigDetails>;
    purchase?:string;
    binBarcode?:string;
    defaultSalesReceivingBin?:boolean;
}
